name: my_first_project
description: A Flutter prototype for the CrushHour experience.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  intl: ^0.20.2
  uuid: ^4.5.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.0.4
  image_picker: ^1.1.2
  flutter_webrtc: ^1.2.1
  firebase_data_connect: ^0.2.2
  cloud_functions: ^6.0.4
  url_launcher: ^6.3.2
  agora_rtc_engine: ^6.3.0
  permission_handler: ^11.3.0
  agora_uikit: ^1.2.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  video_player: ^2.8.7
  file_picker: ^8.1.2

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  
